config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  get 'events/create'
  end

  get 'events/create'

  resources :registered_applications, except: [:edit, :update]
  devise_for :users
  namespace :api, defaults: { format: :json } do
    match '/events', to: 'events#preflight', via: [:options]
    resources :events, only: [:create]
  end
  get 'about' => 'welcome#about'
  root 'welcome#index'
  end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :registered_application
end

app/models/registered_application.rb
class RegisteredApplication < ActiveRecord::Base
  belongs_to :user
  has_many :events
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :registered_applications
  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end
end

app/controllers/api/events_controller.rb
class API::EventsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_access_control_headers
  skip_before_action :authenticate_user!
  respond_to :json

  def set_access_control_headers
    headers['Access-Control-Allow-Origin'] = '*'
    headers['Access-Control-Allow-Methods'] = 'POST, GET, OPTIONS'
    headers['Access-Control-Allow-Headers'] = 'Content-Type'
  end

  def create
    registered_application = RegisteredApplication.find_by(url: request.env['HTTP_ORIGIN'])
    if registered_application == nil
      render json: "Unregistered application", status: :unprocessable_entity
    else
      @event = registered_application.events.build(events_param)
      if @event.save
        render json: "Event create", status: :created
      else
        render json: {errors: @event.errors}, status: :unprocessable_entity
      end
    end
  end

  def preflight
    head 200
  end

  private
  def events_param
    params.require(:event).permit(:name)
  end

  def permission_denied_error
    error(403, 'Permission Denied!')
  end

  def error(status, message = 'Something went wrong')
    response = {
      response_type: "ERROR",
      message: message
    }

    render json: response.to_json, status: status
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/registered_applications_controller.rb
class RegisteredApplicationsController < ApplicationController
  def index
    @registered_applications = current_user.registered_applications
  end

  def show
    @registered_application = current_user.registered_applications.find(params[:id])
    @events = @registered_application.events.group_by(&:name)
  end

  def new
    @registered_application = current_user.registered_applications.new
  end

  def create
    @registered_application = current_user.registered_applications.new
    @registered_application.name = params[:registered_application][:name]
    @registered_application.url = params[:registered_application][:url]

    if @registered_application.save
      flash[:notice] = "New app registered!"
      redirect_to @registered_application
    else
      flash[:alert] = "There was an error registering the app."
      render :new
    end
  end

  def destroy
    @registered_application = current_user.registered_applications.find(params[:id])

    if @registered_application.destroy
      flash[:notice] = "\"#{@registered_application.name}\" was successfully deleted!"
      redirect_to registered_applications_path
    else
      flash[:alert] = "There was an error deleteing the app."
      render :show
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @users = User.all
  end

  def about
  end
end

app/helpers/api/events_helper.rb
module API::EventsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/registered_applications_helper.rb
module RegisteredApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocmetrics</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Blocmetrics", root_path %></li>
        <li><%= link_to "My Applications", registered_applications_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>

      <% if user_signed_in? %>
        Signed in as: <strong><%= current_user.email %></strong> |
        <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
        <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>

      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>

      <%= yield %>
    </div>

  </body>
</html>

app/views/registered_applications/edit.html.erb
<h1>RegisteredApplications#edit</h1>
<p>Find me in app/views/registered_applications/edit.html.erb</p>

app/views/registered_applications/index.html.erb
<h1>All Applications</h1>
<div class="row">
  <div class="col-md-8">
    <% @registered_applications.each do |app| %>
      <div class="media">
        <div class="media-body">
          <div class="media-heading">
            <p><%= app.name %></p>
            <%= link_to "Delete App", app, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this app?' } %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
    <%= link_to "Register New App", new_registered_application_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/registered_applications/new.html.erb
<h1>Register New App</h1>
<div class="row">
  <div class="col-md-8">
    <%= form_for @registered_application do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    <div class="form-group">
      <%= f.label :url %>
      <%= f.text_field :url %>
    </div>
    <div class="form-group">
      <%= f.submit "Save" %>
    </div>
    <% end %>
  </div>
</div>

app/views/registered_applications/show.html.erb
<h1><%= @registered_application.name %></h1>

<div class="row">
  <div class="col-md-8">
    <p><%= @registered_application.url %></p>
    <% @events.each do |event| %>
    <div class="pull-right">
      <%= pie_chart @registered_application.events.group(:name).count %>
    </div>
    <% end %>
  </div>
</div>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Welcome to Blocmetrics</h1>
<h3>Track activity on your apps</h3>

<div class="row">
  <div class="col-md-8">
    <% @users.each do |user| %>
      <div class="media">
        <div class="media-body">
          <div class="media-heading">
            <p><%= user.email %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>